version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: caretrack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: caretrack_pro
      POSTGRES_USER: caretrack
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caretrack -d caretrack_pro"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s